// supracine-angular/src/app/search-movie.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'search-movie',
  templateUrl: './search-movie.component.html',
  styleUrls: ['./search-movie.component.css']
})
export class SearchMovieComponent implements OnInit{
    searchTitle : null|string = "";
    searchYear : null|string = "";
    searchType : null|string = "";
    movieList = [];
    totalResults = 0;
    currentPage : null|string = "1";

    types = [
        {value: "movie", name:"Movie"},
        {value: "series", name:"Series"},
        {value: "episode", name:"Episode"},
        {value: "", name:"All"},
    ];

    constructor(private http: HttpClient, 
        private route: ActivatedRoute,
        private router: Router) { 
    }

    ngOnInit() {
        var params = this.route.snapshot.paramMap
        this.searchTitle = params.get('t') ? params.get('t') : "hero";
        this.searchYear = params.get('y') ? params.get('y') : "2020";
        this.searchType = params.get('type') ? params.get('type') : "movie";
        this.currentPage = params.get('page') ? params.get('page') : "1";

        this.searchMovie(this.currentPage);

    }

    setCurrentPage(page : any){
        this.currentPage = page;
        this.router.navigate([`/search/${this.searchTitle}/${this.searchYear}/${this.searchType}/${this.currentPage}`])
        this.searchMovie(page);
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }

    searchMovie(page : any){
        var source = "http://www.omdbapi.com/?s=" + this.searchTitle + "&y=" + this.searchYear + "&type=" + this.searchType + "&page=" + page + "&apikey=4eacbfee";
        this.http.get<any>(source).subscribe({
            next: data => {
                if(data.Response === "False"){
                    alert("Error! "+ data.Error);
                    this.movieList = [];
                    this.totalResults = 0;
                }else{
                    this.movieList = data.Search;
                    this.totalResults = data.totalResults;
                }
            },
            error: error => {
                alert("Error! "+ error);
                this.movieList = [];
                this.totalResults = 0;
            }
        });

    }
}

<div>  
    <div class="search-field">
        <span>Title: </span><input type="text" name="searchTitle" [(ngModel)]="searchTitle"/>
        <span>Year: </span><input type="text" name="searchYear" [(ngModel)]="searchYear"/>
        <span>Type: </span>
        <select name="searchType" [(ngModel)]="searchType">
            <option *ngFor="let t of types" [value] = "t.value">{{t.name}}</option>
        </select>
        <a routerLink="/search/{{searchTitle}}/{{searchYear}}/{{searchType}}/1" routerLinkActive="active">
            <button type="submit" (click)="searchMovie(1)">Search</button>
        </a>
    </div>
    <movie-list [movieList] = "movieList"></movie-list>
    <div class="clear" ></div> 
    <div class="page-option">
        <page-option [total]="this.totalResults" (setCurrentPage)="setCurrentPage($event)"></page-option>
    </div>
</div>

// supracine-react/src/SearchMovie.js
import React, {Component} from 'react';
import MovieList from './MovieList';
import './SearchMovie.css';
import PageOption from './PageOption';
import { Route, Link, withRouter } from 'react-router-dom';

class SearchMovie extends Component{

    constructor(props){
        super(props);
        this.state = {
            searchTitle: this.props.match.params.t ? this.props.match.params.t : "hero",
            searchYear: this.props.match.params.y ? this.props.match.params.y : 2020,
            searchType: this.props.match.params.type ? this.props.match.params.type : "movie",
            currentPage: this.props.match.params.page ? this.props.match.params.page : 1,
            movieList: [],
            totalResults: 0
        };

        this.searchMovie = this.searchMovie.bind(this);
        this.handleChange = this.handleChange.bind(this);
        this.setCurrentPage = this.setCurrentPage.bind(this);
    }


    componentDidMount() {
        this.searchMovie(this.state.currentPage);
    }

    
    render(){
        return(
            <div>  
                <div className="search-field">
                    <span>Title: </span><input type="text" name="searchTitle" value={this.state.searchTitle} onChange={this.handleChange}/>
                    <span>Year: </span><input type="text" name="searchYear" value={this.state.searchYear} onChange={this.handleChange}/>
                    <span>Type: </span>
                    <select value={this.state.searchType} name="searchType" onChange={this.handleChange}>
                        <option value="movie">Movie</option>
                        <option value="series">Series</option>
                        <option value="episode">Episode</option>
                        <option value="">All</option>
                    </select>
                    <Link to={{pathname : `/search/${this.state.searchTitle}/${this.state.searchYear}/${this.state.searchType}/1`}}>
                        <button type="submit" onClick={this.searchMovie.bind(this,1)}>Search</button>
                    </Link>
                </div>
                <MovieList movieList={this.state.movieList}/>
                <div className="clear" ></div> 
                <div className="page-option">
                    <PageOption total={this.state.totalResults} setCurrentPage={this.setCurrentPage}/>
                </div>
            </div>
        );
    }

    setCurrentPage(page){
        this.setState({
            currentPage : page
        },function(){
            this.searchMovie(page)
            this.props.history.push(`/search/${this.state.searchTitle}/${this.state.searchYear}/${this.state.searchType}/${this.state.currentPage}`);
        });
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }

    searchMovie(page){
        var source = "http://www.omdbapi.com/?s=" + this.state.searchTitle + "&y=" + this.state.searchYear + "&type=" + this.state.searchType + "&page=" + page + "&apikey=4eacbfee";
        fetch(source)
            .then(res => res.json())
            .then(
                (result) => {
                    if(result.Response === "False"){
                        this.setState({
                            movieList: [],
                            totalResults: 0
                        },()=>alert("Error! "+ result.Error));
                    }
                    this.setState({
                        movieList: result.Search,
                        totalResults: result.totalResults
                    });
                },
                (error) => {
                    this.setState({
                        movieList: [],
                        totalResults: 0
                    },()=>alert("Error! "+ error));
                }
            );
    }

    handleChange(e){
        let {name: fieldName, value} = e.target;

        this.setState({
            [fieldName]: value
        });
    }
}

export default withRouter(SearchMovie);
